layout_spectrum: 0.7297872
color:
  saturation: 0.7021171
  brandStrength: 0.2566725
  lightness: 0.6947367
  brandColors:
    - '#BDBBBE'
    - '#CC7093'
    - '#10CDC0'
    - '#1D1515'
    - '#7F9BB3'
  rhythmicContrast: 0.1956322
typography_spectrum: 0.2425532
name: Create A Living
